/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blokgdatabaseapplication;

import Classes.Customer;
import Classes.Employee;
import Classes.Fellow_traveler;
import Classes.Travel;
import Classes.Travel_detail;
import DatabaseControllers.MainController;
import java.awt.List;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author mikey
 */
public class BookingMaken extends javax.swing.JFrame {

    private MainController mc = new MainController();
    private final ArrayList<Customer> customers;
    private final ArrayList<Travel_detail> travel_details;
    private ArrayList<Fellow_traveler> fellow_travelers;
    private HashSet<Fellow_traveler> gaat_mee;
    DefaultListModel<String> modelCustomer;
    DefaultListModel<String> modelTravel_details;
    DefaultListModel<String> modelFellow_travelers;
    DefaultListModel<String> modelGaat_mee;

    /**
     * Creates new form BookingMaken
     */
    public BookingMaken() {
        initComponents();

        customers = mc.getCustomers();
        travel_details = mc.getTravel_detail();
        fellow_travelers = mc.getFellow_travelers();
        gaat_mee = new HashSet();

        modelCustomer = new DefaultListModel<String>();
        for (Customer c : customers) {
            modelCustomer.addElement(c.toString());
        }
        customerList.setModel(modelCustomer);
        customerList.setSelectedIndex(0);

        modelTravel_details = new DefaultListModel<String>();
        for (Travel_detail td : travel_details) {
            modelTravel_details.addElement(td.toString());
        }
        travelDetailList.setModel(modelTravel_details);
        travelDetailList.setSelectedIndex(0);

        modelFellow_travelers = new DefaultListModel<String>();
        for (Fellow_traveler fd : fellow_travelers) {
            modelFellow_travelers.addElement(fd.toString());
        }
        fellowTravelerList.setModel(modelFellow_travelers);
        fellowTravelerList.setSelectedIndex(0);

        modelGaat_mee = new DefaultListModel<String>();
        gaatMeeList.setModel(modelGaat_mee);
        gaatMeeList.setSelectedIndex(0);

    }
    
    private void updateFellow_travelers() {
        modelFellow_travelers.clear();
        fellow_travelers = mc.getFellow_travelers();
        for (Fellow_traveler ft : fellow_travelers) {
            modelFellow_travelers.addElement(ft.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        travelDetailList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fellowTravelerList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jb_gaatMee = new javax.swing.JButton();
        jl_Prijs = new javax.swing.JLabel();
        jlPrijsText = new javax.swing.JLabel();
        jl_StartText = new javax.swing.JLabel();
        jl_EindText = new javax.swing.JLabel();
        jl_Eind = new javax.swing.JLabel();
        jl_Start = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        gaatMeeList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jb_delete = new javax.swing.JButton();
        jlLandText = new javax.swing.JLabel();
        jl_Land = new javax.swing.JLabel();
        jl_BoekerText = new javax.swing.JLabel();
        jl_Boeker = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        tf_birthday = new javax.swing.JTextField();
        jb_medereiziger = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        customerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                customerListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(customerList);

        travelDetailList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        travelDetailList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                travelDetailListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(travelDetailList);

        jButton1.setText("Boek deze reis");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fellowTravelerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(fellowTravelerList);

        jLabel1.setText("Boeker");

        jLabel2.setText("Reis");

        jLabel4.setText("Mogelijke medereizigers");

        jb_gaatMee.setText("Neem mee");
        jb_gaatMee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gaatMeeActionPerformed(evt);
            }
        });

        jl_Prijs.setText("(€1000)");

        jlPrijsText.setText("Prijs:");

        jl_StartText.setText("Start:");

        jl_EindText.setText("Eind:");

        jl_Eind.setText("(einddatum)");

        jl_Start.setText("(startdatum)");

        jScrollPane4.setViewportView(gaatMeeList);

        jLabel3.setText("Gaan mee");

        jb_delete.setText("Verwijder");
        jb_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deleteActionPerformed(evt);
            }
        });

        jlLandText.setText("Land:");

        jl_Land.setText("(landnaam)");

        jl_BoekerText.setText("Boeker:");

        jl_Boeker.setText("(naam)");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Medereiziger toevoegen");

        jLabel6.setText("Voornaam");

        tf_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fnameActionPerformed(evt);
            }
        });

        jLabel7.setText("Achternaam");

        jLabel8.setText("Geslacht");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Man");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Vrouw");

        jLabel9.setText("Geboortedatum (jjjj-mm-dd)");

        tf_birthday.setText("1980-01-01");

        jb_medereiziger.setText("Toevoegen");
        jb_medereiziger.setToolTipText("");
        jb_medereiziger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_medereizigerActionPerformed(evt);
            }
        });
        jb_medereiziger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_medereizigerKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_delete)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_BoekerText)
                                            .addComponent(jl_EindText)
                                            .addComponent(jl_StartText)
                                            .addComponent(jlPrijsText)
                                            .addComponent(jlLandText))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_Boeker)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jl_Prijs)
                                                    .addComponent(jl_Start)
                                                    .addComponent(jl_Eind)))
                                            .addComponent(jl_Land)))))
                            .addComponent(jb_gaatMee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(tf_fname)
                            .addComponent(jLabel7)
                            .addComponent(tf_lname)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_birthday)
                            .addComponent(jb_medereiziger, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_BoekerText)
                                            .addComponent(jl_Boeker))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlLandText)
                                            .addComponent(jl_Land))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_Prijs)
                                            .addComponent(jlPrijsText))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_StartText)
                                            .addComponent(jl_Start))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_EindText)
                                            .addComponent(jl_Eind))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_medereiziger)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_gaatMee)
                    .addComponent(jb_delete))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int customer_index = this.customerList.getSelectedIndex();
        int travel_detail_index = this.travelDetailList.getSelectedIndex();
        int customer_id = customers.get(customer_index).getCustomer_id();
        int travel_detail_id = travel_details.get(travel_detail_index).getTravel_detail_id();
        JOptionPane.showMessageDialog(this, "Reis naar " + travel_details.get(travel_detail_index).getCountry() + " geboekt met booking id " + mc.createBooking(travel_detail_id, customer_id, gaat_mee) +".");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_gaatMeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gaatMeeActionPerformed
        int ft_index = fellowTravelerList.getSelectedIndex();
        gaat_mee.add(fellow_travelers.get(ft_index));
        updateGaatMee();
    }//GEN-LAST:event_jb_gaatMeeActionPerformed

    private void updateGaatMee() {
        modelGaat_mee.clear();
        for (Fellow_traveler ft : gaat_mee) {
            modelGaat_mee.addElement(ft.toString());
        }
    }

    private void travelDetailListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_travelDetailListValueChanged
        if (!evt.getValueIsAdjusting()) {
            int travel_detail_index = this.travelDetailList.getSelectedIndex();
            String land = travel_details.get(travel_detail_index).getCountry();
            double travel_price = travel_details.get(travel_detail_index).getPrice();
            Date start_date = travel_details.get(travel_detail_index).getStart_date();
            Date end_date = travel_details.get(travel_detail_index).getEnd_date();
            jl_Land.setText(land);
            jl_Prijs.setText(Double.toString(travel_price));
            jl_Start.setText(start_date.toString());
            jl_Eind.setText(end_date.toString());
        }
    }//GEN-LAST:event_travelDetailListValueChanged

    private void jb_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deleteActionPerformed
        int ft_index = gaatMeeList.getSelectedIndex();
        ArrayList<Fellow_traveler> delete_array = new ArrayList<>(gaat_mee);
        Fellow_traveler delete = delete_array.get(ft_index);
        gaat_mee.remove(delete);
        updateGaatMee();
    }//GEN-LAST:event_jb_deleteActionPerformed

    private void customerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_customerListValueChanged
        if (!evt.getValueIsAdjusting()) {
            int customer_index = this.customerList.getSelectedIndex();
            String customer_name = customers.get(customer_index).toString();
            jl_Boeker.setText(customer_name);
        }
    }//GEN-LAST:event_customerListValueChanged

    private void tf_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fnameActionPerformed

    private void jb_medereizigerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_medereizigerKeyPressed

    }//GEN-LAST:event_jb_medereizigerKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jb_medereizigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_medereizigerActionPerformed
        String fname = tf_fname.getText();
        String lname = tf_lname.getText();
        String sex = null;
        if (jRadioButton1.isSelected()) {
            sex = "M";
        } else {
            sex = "F";
        }
        String birthday = tf_birthday.getText();
        if (!fname.equals("") && !lname.equals("") && !birthday.equals("")) {
            if (mc.createFellow_traveler(fname, lname, sex, birthday)) {
                JOptionPane.showMessageDialog(this, "Medereiziger is toegevoegd.");
                updateFellow_travelers();
            } else {
                JOptionPane.showMessageDialog(this, "Medereiziger is niet toegevoegd.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Velden incompleet.");
        }
    }//GEN-LAST:event_jb_medereizigerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingMaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingMaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingMaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingMaken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingMaken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> customerList;
    private javax.swing.JList<String> fellowTravelerList;
    private javax.swing.JList<String> gaatMeeList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_delete;
    private javax.swing.JButton jb_gaatMee;
    private javax.swing.JButton jb_medereiziger;
    private javax.swing.JLabel jlLandText;
    private javax.swing.JLabel jlPrijsText;
    private javax.swing.JLabel jl_Boeker;
    private javax.swing.JLabel jl_BoekerText;
    private javax.swing.JLabel jl_Eind;
    private javax.swing.JLabel jl_EindText;
    private javax.swing.JLabel jl_Land;
    private javax.swing.JLabel jl_Prijs;
    private javax.swing.JLabel jl_Start;
    private javax.swing.JLabel jl_StartText;
    private javax.swing.JTextField tf_birthday;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_lname;
    private javax.swing.JList<String> travelDetailList;
    // End of variables declaration//GEN-END:variables
}
